name: Build & Deploy website

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORGANIZATION_ID }}
      VERCEL_PROJECT_ID: prj_ql9ijtBGTGHYKYWS8aJKfGggtuli
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}